puts "john".object_id
puts "john".object_id
puts "john".object_id
puts "john".object_id
puts "john".object_id
puts "_______________"
puts :john.object_id
puts :john.object_id
puts :john.object_id
puts :john.object_id
puts :john.object_id